'use strict'

var db = require('./../schema');

exports.up = function(next) {
    db.marca.create([
        {descricao: 'Acura'},
        {descricao: 'Agrale'},
        {descricao: 'Alfa Romeo'},
        {descricao: 'Americar'},
        {descricao: 'Asia'},
        {descricao: 'Aston Martin'},
        {descricao: 'Audi'},
        {descricao: 'Austin-healey'},
        {descricao: 'Avallone'},
        {descricao: 'Baja'},
        {descricao: 'Bentley'},
        {descricao: 'Bmw'},
        {descricao: 'Brm'},
        {descricao: 'Bugre'},
        {descricao: 'Bugway'},
        {descricao: 'Buick'},
        {descricao: 'Cadillac'},
        {descricao: 'Cbt'},
        {descricao: 'Chamonix'},
        {descricao: 'Chana'},
        {descricao: 'Changan'},
        {descricao: 'Chery'},
        {descricao: 'Chevrolet'},
        {descricao: 'Chrysler'},
        {descricao: 'Citroën'},
        {descricao: 'Dacon'},
        {descricao: 'Daewoo'},
        {descricao: 'Daihatsu'},
        {descricao: 'De Soto'},
        {descricao: 'Delorean'},
        {descricao: 'Dkw-vemag'},
        {descricao: 'Dodge'},
        {descricao: 'Effa'},
        {descricao: 'Emis'},
        {descricao: 'Engesa'},
        {descricao: 'Envemo'},
        {descricao: 'Fercar Buggy'},
        {descricao: 'Ferrari'},
        {descricao: 'Fiat'},
        {descricao: 'Ford'},
        {descricao: 'Foton'},
        {descricao: 'Fyber'},
        {descricao: 'Geely'},
        {descricao: 'Geo'},
        {descricao: 'Gmc'},
        {descricao: 'Gurgel'},
        {descricao: 'Hafei'},
        {descricao: 'Honda'},
        {descricao: 'Hudson'},
        {descricao: 'Hummer'},
        {descricao: 'Hyundai'},
        {descricao: 'Infiniti'},
        {descricao: 'International'},
        {descricao: 'Iveco'},
        {descricao: 'Jac'},
        {descricao: 'Jaguar'},
        {descricao: 'Jeep'},
        {descricao: 'Jinbei'},
        {descricao: 'Jpx'},
        {descricao: 'Kaiser'},
        {descricao: 'Kia'},
        {descricao: 'Lada'},
        {descricao: 'Lamborghini'},
        {descricao: 'Land Rover'},
        {descricao: 'Landwind'},
        {descricao: 'Lexus'},
        {descricao: 'Lifan'},
        {descricao: 'Lincoln'},
        {descricao: 'Lobini'},
        {descricao: 'Lotus'},
        {descricao: 'Mahindra'},
        {descricao: 'Marcopolo'},
        {descricao: 'Maserati'},
        {descricao: 'Matra'},
        {descricao: 'Mazda'},
        {descricao: 'Mclaren'},
        {descricao: 'Mercedes-benz'},
        {descricao: 'Mercury'},
        {descricao: 'Mg'},
        {descricao: 'Mini'},
        {descricao: 'Mitsubishi'},
        {descricao: 'Miura'},
        {descricao: 'Morris'},
        {descricao: 'Mp Lafer'},
        {descricao: 'Nissan'},
        {descricao: 'Oldsmobile'},
        {descricao: 'Opel'},
        {descricao: 'Packard'},
        {descricao: 'Pag'},
        {descricao: 'Peugeot'},
        {descricao: 'Plymouth'},
        {descricao: 'Pontiac'},
        {descricao: 'Porsche'},
        {descricao: 'Puma'},
        {descricao: 'Rely'},
        {descricao: 'Renault'},
        {descricao: 'Reva-i'},
        {descricao: 'Rolls-royce'},
        {descricao: 'Romi'},
        {descricao: 'Saab'},
        {descricao: 'Santa Matilde'},
        {descricao: 'Saturn'},
        {descricao: 'Seat'},
        {descricao: 'Selvagem'},
        {descricao: 'Shelby'},
        {descricao: 'Shineray'},
        {descricao: 'Smart'},
        {descricao: 'Ssangyong'},
        {descricao: 'Standard'},
        {descricao: 'Studebaker'},
        {descricao: 'Subaru'},
        {descricao: 'Suzuki'},
        {descricao: 'Tac'},
        {descricao: 'Tesla'},
        {descricao: 'Toyota'},
        {descricao: 'Triumph'},
        {descricao: 'Troller'},
        {descricao: 'Volkswagen'},
        {descricao: 'Volvo'},
        {descricao: 'Way Brasil'},
        {descricao: 'Whippet'},
        {descricao: 'Willys'},
        {descricao: 'Willys Overland'}
    ],
    function(err) {
        if (err) throw err;
        next();
    });
};

exports.down = function(next) {
    db.marca.find().remove(function(err) {
        if (err) throw err;
        next();
    });
};
