'use strict'

var db = require('./../schema');

exports.up = function(next) {
    db.marca.find(function(err, marcas) {
        if (err) throw err;

        var marcasPorDescricao = {};

        for (var i = 0; i < marcas.length; i++) {
            marcasPorDescricao[marcas[i].descricao] = marcas[i]._id;
        }

        db.modelo.create([
            {fk_marca: marcasPorDescricao["Acura"], descricao: "LEGEND"},
            {fk_marca: marcasPorDescricao["Agrale"], descricao: "FURGOVAN"},
            {fk_marca: marcasPorDescricao["Agrale"], descricao: "MARRUÁ"},
            {fk_marca: marcasPorDescricao["Alfa Romeo"], descricao: "145"},
            {fk_marca: marcasPorDescricao["Alfa Romeo"], descricao: "147"},
            {fk_marca: marcasPorDescricao["Alfa Romeo"], descricao: "155"},
            {fk_marca: marcasPorDescricao["Alfa Romeo"], descricao: "156"},
            {fk_marca: marcasPorDescricao["Alfa Romeo"], descricao: "164"},
            {fk_marca: marcasPorDescricao["Alfa Romeo"], descricao: "166"},
            {fk_marca: marcasPorDescricao["Alfa Romeo"], descricao: "2300 Ti"},
            {fk_marca: marcasPorDescricao["Alfa Romeo"], descricao: "4C"},
            {fk_marca: marcasPorDescricao["Alfa Romeo"], descricao: "SPIDER"},
            {fk_marca: marcasPorDescricao["Americar"], descricao: "CLASSIC 427"},
            {fk_marca: marcasPorDescricao["Americar"], descricao: "CLASSIC XK120"},
            {fk_marca: marcasPorDescricao["Asia"], descricao: "HI-TOPIC"},
            {fk_marca: marcasPorDescricao["Asia"], descricao: "ROCSTA"},
            {fk_marca: marcasPorDescricao["Asia"], descricao: "TOPIC"},
            {fk_marca: marcasPorDescricao["Asia"], descricao: "TOWNER"},
            {fk_marca: marcasPorDescricao["Aston Martin"], descricao: "DB7"},
            {fk_marca: marcasPorDescricao["Aston Martin"], descricao: "DB9"},
            {fk_marca: marcasPorDescricao["Aston Martin"], descricao: "DBS"},
            {fk_marca: marcasPorDescricao["Aston Martin"], descricao: "RAPIDE"},
            {fk_marca: marcasPorDescricao["Aston Martin"], descricao: "V12 VANTAGE"},
            {fk_marca: marcasPorDescricao["Aston Martin"], descricao: "VANQUISH"},
            {fk_marca: marcasPorDescricao["Aston Martin"], descricao: "VANTAGE"},
            {fk_marca: marcasPorDescricao["Aston Martin"], descricao: "VIRAGE"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "80"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "A1"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "A2"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "A3"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "A4"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "A5"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "A6"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "A7"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "A8"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "ALLROAD"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "Q3"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "Q5"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "Q7"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "R8"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "RS Q3"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "RS2"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "RS3"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "RS4"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "RS5"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "RS6"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "RS7"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "S3"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "S4"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "S5"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "S6"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "S7"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "S8"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "SQ5"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "TT"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "TT RS"},
            {fk_marca: marcasPorDescricao["Audi"], descricao: "TTS"},
            {fk_marca: marcasPorDescricao["Austin-healey"], descricao: "3000"},
            {fk_marca: marcasPorDescricao["Avallone"], descricao: "TF"},
            {fk_marca: marcasPorDescricao["Baja"], descricao: "BUGGY"},
            {fk_marca: marcasPorDescricao["Bentley"], descricao: "BROOKLANDS"},
            {fk_marca: marcasPorDescricao["Bentley"], descricao: "CONTINENTAL"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "1 M"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "116i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "118i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "120i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "125i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "130i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "135i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "220i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "225i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "316i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "318i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "318Ti"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "320i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "323Ci"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "323i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "323Ti"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "325Ci"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "325i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "325iS"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "328i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "330i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "335"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "335i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "420i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "428i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "435i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "525i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "528i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "530i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "535i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "540i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "545i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "550i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "635CSi"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "640i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "645CI"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "650Ci"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "650i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "740i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "740iL"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "745i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "750i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "760Li"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "850Ci"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "850CSi"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "i3"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "i8"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "ISETTA"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "M 135i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "M235i"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "M3"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "M4"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "M5"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "M6"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "X1"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "X3"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "X4"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "X5"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "X6"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "Z3"},
            {fk_marca: marcasPorDescricao["Bmw"], descricao: "Z4"},
            {fk_marca: marcasPorDescricao["Brm"], descricao: "M-10 1/2"},
            {fk_marca: marcasPorDescricao["Brm"], descricao: "M-11"},
            {fk_marca: marcasPorDescricao["Brm"], descricao: "M-8"},
            {fk_marca: marcasPorDescricao["Bugre"], descricao: "M150"},
            {fk_marca: marcasPorDescricao["Bugway"], descricao: "BUGGY"},
            {fk_marca: marcasPorDescricao["Buick"], descricao: "DINAFLOW"},
            {fk_marca: marcasPorDescricao["Buick"], descricao: "LACROSSE"},
            {fk_marca: marcasPorDescricao["Buick"], descricao: "LESABRE"},
            {fk_marca: marcasPorDescricao["Buick"], descricao: "PARK AVENUE"},
            {fk_marca: marcasPorDescricao["Buick"], descricao: "REGAL"},
            {fk_marca: marcasPorDescricao["Cadillac"], descricao: "CTS"},
            {fk_marca: marcasPorDescricao["Cadillac"], descricao: "CTS-V"},
            {fk_marca: marcasPorDescricao["Cadillac"], descricao: "DE VILLE"},
            {fk_marca: marcasPorDescricao["Cadillac"], descricao: "ELDORADO"},
            {fk_marca: marcasPorDescricao["Cadillac"], descricao: "ESCALADE"},
            {fk_marca: marcasPorDescricao["Cadillac"], descricao: "FLEETWOOD"},
            {fk_marca: marcasPorDescricao["Cadillac"], descricao: "SERIES 62"},
            {fk_marca: marcasPorDescricao["Cadillac"], descricao: "SEVILLE"},
            {fk_marca: marcasPorDescricao["Cadillac"], descricao: "SRX"},
            {fk_marca: marcasPorDescricao["Cbt"], descricao: "JEEP"},
            {fk_marca: marcasPorDescricao["Chamonix"], descricao: "SPYDER"},
            {fk_marca: marcasPorDescricao["Chamonix"], descricao: "SUPER 90"},
            {fk_marca: marcasPorDescricao["Chana"], descricao: "CARGO"},
            {fk_marca: marcasPorDescricao["Chana"], descricao: "UTILITY"},
            {fk_marca: marcasPorDescricao["Changan"], descricao: "MINISTAR"},
            {fk_marca: marcasPorDescricao["Chery"], descricao: "CELER"},
            {fk_marca: marcasPorDescricao["Chery"], descricao: "CIELO"},
            {fk_marca: marcasPorDescricao["Chery"], descricao: "FACE"},
            {fk_marca: marcasPorDescricao["Chery"], descricao: "QQ"},
            {fk_marca: marcasPorDescricao["Chery"], descricao: "S-18"},
            {fk_marca: marcasPorDescricao["Chery"], descricao: "TIGGO"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "A10"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "A20"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "ADVANCED DESIGN"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "AGILE"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "ASTRA"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "ASTROVAN"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "BEL AIR"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "BLAZER"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "BONANZA"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "BRASIL"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "BRASINCA"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "C10"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "C14"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "C15"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "C20"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "CALIBRA"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "CAMARO"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "CAPRICE"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "CAPTIVA"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "CARAVAN"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "CAVALIER"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "CELTA"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "CHEVELLE"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "CHEVETTE"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "CHEVY 500"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "CHEYENNE"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "CLASSIC"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "COBALT"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "CORSA"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "CORVETTE"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "CORVETTE GRAND SPORT"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "CRUZE"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "D10"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "D20"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "D40"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "DE LUXE"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "EL CAMINO"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "FLEETMASTER"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "GRAND BLAZER"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "HHR"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "IMPALA"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "IPANEMA"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "KADETT"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "LUMINA"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "MALIBU"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "MARAJÓ"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "MASTER"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "MERIVA"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "MONTANA"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "MONZA"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "OMEGA"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "ONIX"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "OPALA"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "PICKUP"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "PRISMA"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "RAMONA"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "S10"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "SILVERADO"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "SONIC"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "SPACE VAN"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "SPIN"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "SPORT VAN"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "SS"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "SSR"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "STYLEMASTER"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "SUBURBAN"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "SUPREMA"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "TAHOE"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "TIGRA"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "TRACKER"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "TRAFIC"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "TRAILBLAZER"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "TRAVERSE"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "VECTRA"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "VERANEIO"},
            {fk_marca: marcasPorDescricao["Chevrolet"], descricao: "ZAFIRA"},
            {fk_marca: marcasPorDescricao["Chrysler"], descricao: "300 C"},
            {fk_marca: marcasPorDescricao["Chrysler"], descricao: "300 M"},
            {fk_marca: marcasPorDescricao["Chrysler"], descricao: "CARAVAN"},
            {fk_marca: marcasPorDescricao["Chrysler"], descricao: "CORDOBA"},
            {fk_marca: marcasPorDescricao["Chrysler"], descricao: "ESPLANADA"},
            {fk_marca: marcasPorDescricao["Chrysler"], descricao: "GRAND CARAVAN"},
            {fk_marca: marcasPorDescricao["Chrysler"], descricao: "NEON"},
            {fk_marca: marcasPorDescricao["Chrysler"], descricao: "PT CRUISER"},
            {fk_marca: marcasPorDescricao["Chrysler"], descricao: "SEBRING"},
            {fk_marca: marcasPorDescricao["Chrysler"], descricao: "STRATUS"},
            {fk_marca: marcasPorDescricao["Chrysler"], descricao: "TOWN & COUNTRY"},
            {fk_marca: marcasPorDescricao["Citroën"], descricao: "AIRCROSS"},
            {fk_marca: marcasPorDescricao["Citroën"], descricao: "BERLINGO"},
            {fk_marca: marcasPorDescricao["Citroën"], descricao: "C3"},
            {fk_marca: marcasPorDescricao["Citroën"], descricao: "C3 SONORA"},
            {fk_marca: marcasPorDescricao["Citroën"], descricao: "C4"},
            {fk_marca: marcasPorDescricao["Citroën"], descricao: "C4 LOUNGE"},
            {fk_marca: marcasPorDescricao["Citroën"], descricao: "C4 PICASSO"},
            {fk_marca: marcasPorDescricao["Citroën"], descricao: "C5"},
            {fk_marca: marcasPorDescricao["Citroën"], descricao: "C6"},
            {fk_marca: marcasPorDescricao["Citroën"], descricao: "C8"},
            {fk_marca: marcasPorDescricao["Citroën"], descricao: "DS3"},
            {fk_marca: marcasPorDescricao["Citroën"], descricao: "DS4"},
            {fk_marca: marcasPorDescricao["Citroën"], descricao: "DS5"},
            {fk_marca: marcasPorDescricao["Citroën"], descricao: "EVASION"},
            {fk_marca: marcasPorDescricao["Citroën"], descricao: "GRAND C4"},
            {fk_marca: marcasPorDescricao["Citroën"], descricao: "JUMPER"},
            {fk_marca: marcasPorDescricao["Citroën"], descricao: "TRACTION AVANT"},
            {fk_marca: marcasPorDescricao["Citroën"], descricao: "XANTIA"},
            {fk_marca: marcasPorDescricao["Citroën"], descricao: "XM"},
            {fk_marca: marcasPorDescricao["Citroën"], descricao: "XSARA"},
            {fk_marca: marcasPorDescricao["Citroën"], descricao: "XSARA PICASSO"},
            {fk_marca: marcasPorDescricao["Dacon"], descricao: "828"},
            {fk_marca: marcasPorDescricao["Daewoo"], descricao: "ESPERO"},
            {fk_marca: marcasPorDescricao["Daewoo"], descricao: "LANOS"},
            {fk_marca: marcasPorDescricao["Daihatsu"], descricao: "FEROZA"},
            {fk_marca: marcasPorDescricao["Daihatsu"], descricao: "GRAN MOVE"},
            {fk_marca: marcasPorDescricao["Daihatsu"], descricao: "TERIOS"},
            {fk_marca: marcasPorDescricao["De Soto"], descricao: "DE SOTO"},
            {fk_marca: marcasPorDescricao["Delorean"], descricao: "DMC-12"},
            {fk_marca: marcasPorDescricao["Dkw-vemag"], descricao: "BELCAR"},
            {fk_marca: marcasPorDescricao["Dkw-vemag"], descricao: "FISSORE"},
            {fk_marca: marcasPorDescricao["Dodge"], descricao: "CALIBER"},
            {fk_marca: marcasPorDescricao["Dodge"], descricao: "CHALLENGER"},
            {fk_marca: marcasPorDescricao["Dodge"], descricao: "CHARGER"},
            {fk_marca: marcasPorDescricao["Dodge"], descricao: "DAKOTA"},
            {fk_marca: marcasPorDescricao["Dodge"], descricao: "DART"},
            {fk_marca: marcasPorDescricao["Dodge"], descricao: "DURANGO"},
            {fk_marca: marcasPorDescricao["Dodge"], descricao: "GRAND CARAVAN"},
            {fk_marca: marcasPorDescricao["Dodge"], descricao: "JOURNEY"},
            {fk_marca: marcasPorDescricao["Dodge"], descricao: "LE BARON"},
            {fk_marca: marcasPorDescricao["Dodge"], descricao: "MAGNUM"},
            {fk_marca: marcasPorDescricao["Dodge"], descricao: "NITRO"},
            {fk_marca: marcasPorDescricao["Dodge"], descricao: "POLARA"},
            {fk_marca: marcasPorDescricao["Dodge"], descricao: "RAM"},
            {fk_marca: marcasPorDescricao["Dodge"], descricao: "STEALTH"},
            {fk_marca: marcasPorDescricao["Dodge"], descricao: "TRAZO"},
            {fk_marca: marcasPorDescricao["Dodge"], descricao: "VIPER"},
            {fk_marca: marcasPorDescricao["Effa"], descricao: "FURGÃO"},
            {fk_marca: marcasPorDescricao["Effa"], descricao: "M100"},
            {fk_marca: marcasPorDescricao["Effa"], descricao: "PICAPE CABINE DUPLA"},
            {fk_marca: marcasPorDescricao["Effa"], descricao: "PICAPE CAÇAMBA CURTA"},
            {fk_marca: marcasPorDescricao["Effa"], descricao: "PICAPE CAÇAMBA LONGA"},
            {fk_marca: marcasPorDescricao["Effa"], descricao: "PICAPE CAÇAMBA LONGA BAÚ"},
            {fk_marca: marcasPorDescricao["Effa"], descricao: "PICAPE PLUTUS"},
            {fk_marca: marcasPorDescricao["Effa"], descricao: "PICAPE START CABINE DUPLA"},
            {fk_marca: marcasPorDescricao["Effa"], descricao: "PICAPE START LONGA"},
            {fk_marca: marcasPorDescricao["Effa"], descricao: "VAN"},
            {fk_marca: marcasPorDescricao["Effa"], descricao: "VAN START"},
            {fk_marca: marcasPorDescricao["Emis"], descricao: "BUGGY"},
            {fk_marca: marcasPorDescricao["Engesa"], descricao: "ENGESA"},
            {fk_marca: marcasPorDescricao["Engesa"], descricao: "ENGESA 4"},
            {fk_marca: marcasPorDescricao["Envemo"], descricao: "CAMPER"},
            {fk_marca: marcasPorDescricao["Envemo"], descricao: "SUPER 90"},
            {fk_marca: marcasPorDescricao["Fercar Buggy"], descricao: "NAJA ONE"},
            {fk_marca: marcasPorDescricao["Ferrari"], descricao: "308"},
            {fk_marca: marcasPorDescricao["Ferrari"], descricao: "328 GTB"},
            {fk_marca: marcasPorDescricao["Ferrari"], descricao: "348"},
            {fk_marca: marcasPorDescricao["Ferrari"], descricao: "458 ITALIA"},
            {fk_marca: marcasPorDescricao["Ferrari"], descricao: "458 SPECIALE"},
            {fk_marca: marcasPorDescricao["Ferrari"], descricao: "458 SPIDER"},
            {fk_marca: marcasPorDescricao["Ferrari"], descricao: "488 GTB"},
            {fk_marca: marcasPorDescricao["Ferrari"], descricao: "599 GTB"},
            {fk_marca: marcasPorDescricao["Ferrari"], descricao: "612"},
            {fk_marca: marcasPorDescricao["Ferrari"], descricao: "CALIFORNIA"},
            {fk_marca: marcasPorDescricao["Ferrari"], descricao: "F12BERLINETTA"},
            {fk_marca: marcasPorDescricao["Ferrari"], descricao: "F355"},
            {fk_marca: marcasPorDescricao["Ferrari"], descricao: "F355 F1"},
            {fk_marca: marcasPorDescricao["Ferrari"], descricao: "F360"},
            {fk_marca: marcasPorDescricao["Ferrari"], descricao: "F430"},
            {fk_marca: marcasPorDescricao["Ferrari"], descricao: "F456"},
            {fk_marca: marcasPorDescricao["Ferrari"], descricao: "FF"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "147"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "500"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "600"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "BRAVA"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "BRAVO"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "CINQUECENTO"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "COUPÉ"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "DOBLÒ"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "DUCATO"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "ELBA"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "FIORINO"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "FREEMONT"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "GRAND SIENA"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "IDEA"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "LINEA"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "MAREA"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "OGGI"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "PALIO"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "PANORAMA"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "PREMIO"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "PUNTO"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "SIENA"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "SPAZIO"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "STILO"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "STRADA"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "TEMPRA"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "TIPO"},
            {fk_marca: marcasPorDescricao["Fiat"], descricao: "UNO"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "A"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "BELINA"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "CLUB WAGON"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "CORCEL"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "CORCEL II"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "COURIER"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "CROWN VICTORIA"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "CUPÊ"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "CUSTOM"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "DEL REY"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "ECOSPORT"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "EDGE"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "ESCAPE"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "ESCORT"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "EXPEDITION"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "EXPLORER"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "F-1"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "F-100"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "F-1000"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "F-150"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "F-250"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "F-350"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "F-4000"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "F-75"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "FAIRLANE"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "FIESTA"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "FLEX"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "FOCUS"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "FUSION"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "GALAXIE"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "IBIZA"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "JEEP"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "KA"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "KA +"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "LANDAU"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "MAVERICK"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "MONDEO"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "MUSTANG"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "MUSTANG V6"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "PAMPA"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "PHAETON"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "RANCHERO"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "RANGER"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "ROYALE"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "RURAL"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "SUPER DELUXE"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "T"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "TAURUS"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "THUNDERBIRD"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "TRANSIT"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "TUDOR"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "VERONA"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "VERSAILLES"},
            {fk_marca: marcasPorDescricao["Ford"], descricao: "WINDSTAR"},
            {fk_marca: marcasPorDescricao["Foton"], descricao: "AUMARK 3.5"},
            {fk_marca: marcasPorDescricao["Fyber"], descricao: "2000W"},
            {fk_marca: marcasPorDescricao["Geely"], descricao: "EC7"},
            {fk_marca: marcasPorDescricao["Geely"], descricao: "GC2"},
            {fk_marca: marcasPorDescricao["Geo"], descricao: "STORM"},
            {fk_marca: marcasPorDescricao["Gmc"], descricao: "3500 HD"},
            {fk_marca: marcasPorDescricao["Gmc"], descricao: "BLAZER"},
            {fk_marca: marcasPorDescricao["Gmc"], descricao: "ENVOY"},
            {fk_marca: marcasPorDescricao["Gmc"], descricao: "SIERRA"},
            {fk_marca: marcasPorDescricao["Gmc"], descricao: "SILVERADO"},
            {fk_marca: marcasPorDescricao["Gmc"], descricao: "SONOMA"},
            {fk_marca: marcasPorDescricao["Gurgel"], descricao: "BR-800"},
            {fk_marca: marcasPorDescricao["Gurgel"], descricao: "SUPERMINI"},
            {fk_marca: marcasPorDescricao["Gurgel"], descricao: "X12"},
            {fk_marca: marcasPorDescricao["Hafei"], descricao: "TOWNER"},
            {fk_marca: marcasPorDescricao["Hafei"], descricao: "TOWNER JR"},
            {fk_marca: marcasPorDescricao["Honda"], descricao: "ACCORD"},
            {fk_marca: marcasPorDescricao["Honda"], descricao: "CITY"},
            {fk_marca: marcasPorDescricao["Honda"], descricao: "CIVIC"},
            {fk_marca: marcasPorDescricao["Honda"], descricao: "CRV"},
            {fk_marca: marcasPorDescricao["Honda"], descricao: "FIT"},
            {fk_marca: marcasPorDescricao["Honda"], descricao: "HR-V"},
            {fk_marca: marcasPorDescricao["Honda"], descricao: "LEGEND"},
            {fk_marca: marcasPorDescricao["Honda"], descricao: "PRELUDE"},
            {fk_marca: marcasPorDescricao["Hudson"], descricao: "HORNET"},
            {fk_marca: marcasPorDescricao["Hummer"], descricao: "H1"},
            {fk_marca: marcasPorDescricao["Hummer"], descricao: "H2"},
            {fk_marca: marcasPorDescricao["Hummer"], descricao: "H3"},
            {fk_marca: marcasPorDescricao["Hyundai"], descricao: "ACCENT"},
            {fk_marca: marcasPorDescricao["Hyundai"], descricao: "ATOS"},
            {fk_marca: marcasPorDescricao["Hyundai"], descricao: "AZERA"},
            {fk_marca: marcasPorDescricao["Hyundai"], descricao: "COUPÊ"},
            {fk_marca: marcasPorDescricao["Hyundai"], descricao: "ELANTRA"},
            {fk_marca: marcasPorDescricao["Hyundai"], descricao: "EQUUS"},
            {fk_marca: marcasPorDescricao["Hyundai"], descricao: "GALLOPER"},
            {fk_marca: marcasPorDescricao["Hyundai"], descricao: "GENESIS"},
            {fk_marca: marcasPorDescricao["Hyundai"], descricao: "GRAND SANTA FÉ"},
            {fk_marca: marcasPorDescricao["Hyundai"], descricao: "H1 STAREX"},
            {fk_marca: marcasPorDescricao["Hyundai"], descricao: "H100"},
            {fk_marca: marcasPorDescricao["Hyundai"], descricao: "HB20"},
            {fk_marca: marcasPorDescricao["Hyundai"], descricao: "HB20S"},
            {fk_marca: marcasPorDescricao["Hyundai"], descricao: "HB20X"},
            {fk_marca: marcasPorDescricao["Hyundai"], descricao: "HR"},
            {fk_marca: marcasPorDescricao["Hyundai"], descricao: "I30"},
            {fk_marca: marcasPorDescricao["Hyundai"], descricao: "I30 CW"},
            {fk_marca: marcasPorDescricao["Hyundai"], descricao: "IX35"},
            {fk_marca: marcasPorDescricao["Hyundai"], descricao: "SANTA FÉ"},
            {fk_marca: marcasPorDescricao["Hyundai"], descricao: "SONATA"},
            {fk_marca: marcasPorDescricao["Hyundai"], descricao: "TERRACAN"},
            {fk_marca: marcasPorDescricao["Hyundai"], descricao: "TIBURON"},
            {fk_marca: marcasPorDescricao["Hyundai"], descricao: "TUCSON"},
            {fk_marca: marcasPorDescricao["Hyundai"], descricao: "VELOSTER"},
            {fk_marca: marcasPorDescricao["Hyundai"], descricao: "VERA CRUZ"},
            {fk_marca: marcasPorDescricao["Infiniti"], descricao: "EX35"},
            {fk_marca: marcasPorDescricao["Infiniti"], descricao: "FX35"},
            {fk_marca: marcasPorDescricao["Infiniti"], descricao: "FX37"},
            {fk_marca: marcasPorDescricao["Infiniti"], descricao: "FX45"},
            {fk_marca: marcasPorDescricao["Infiniti"], descricao: "FX50"},
            {fk_marca: marcasPorDescricao["Infiniti"], descricao: "QX56"},
            {fk_marca: marcasPorDescricao["Infiniti"], descricao: "QX70"},
            {fk_marca: marcasPorDescricao["International"], descricao: "KB2"},
            {fk_marca: marcasPorDescricao["Iveco"], descricao: "DAILY"},
            {fk_marca: marcasPorDescricao["Jac"], descricao: "J2"},
            {fk_marca: marcasPorDescricao["Jac"], descricao: "J3"},
            {fk_marca: marcasPorDescricao["Jac"], descricao: "J5"},
            {fk_marca: marcasPorDescricao["Jac"], descricao: "J6"},
            {fk_marca: marcasPorDescricao["Jac"], descricao: "T140"},
            {fk_marca: marcasPorDescricao["Jac"], descricao: "T6"},
            {fk_marca: marcasPorDescricao["Jac"], descricao: "T8"},
            {fk_marca: marcasPorDescricao["Jaguar"], descricao: "E-TYPE"},
            {fk_marca: marcasPorDescricao["Jaguar"], descricao: "F-TYPE"},
            {fk_marca: marcasPorDescricao["Jaguar"], descricao: "S-TYPE"},
            {fk_marca: marcasPorDescricao["Jaguar"], descricao: "XE"},
            {fk_marca: marcasPorDescricao["Jaguar"], descricao: "XF"},
            {fk_marca: marcasPorDescricao["Jaguar"], descricao: "XFR"},
            {fk_marca: marcasPorDescricao["Jaguar"], descricao: "XJ"},
            {fk_marca: marcasPorDescricao["Jaguar"], descricao: "XJ6"},
            {fk_marca: marcasPorDescricao["Jaguar"], descricao: "XJ8"},
            {fk_marca: marcasPorDescricao["Jaguar"], descricao: "XJ-S"},
            {fk_marca: marcasPorDescricao["Jaguar"], descricao: "XK 120"},
            {fk_marca: marcasPorDescricao["Jaguar"], descricao: "XK8"},
            {fk_marca: marcasPorDescricao["Jaguar"], descricao: "XKR"},
            {fk_marca: marcasPorDescricao["Jaguar"], descricao: "XKR-S"},
            {fk_marca: marcasPorDescricao["Jaguar"], descricao: "X-TYPE"},
            {fk_marca: marcasPorDescricao["Jeep"], descricao: "CHEROKEE"},
            {fk_marca: marcasPorDescricao["Jeep"], descricao: "CJ 5"},
            {fk_marca: marcasPorDescricao["Jeep"], descricao: "COMMANDER"},
            {fk_marca: marcasPorDescricao["Jeep"], descricao: "COMPASS"},
            {fk_marca: marcasPorDescricao["Jeep"], descricao: "GRAND CHEROKEE"},
            {fk_marca: marcasPorDescricao["Jeep"], descricao: "PATRIOT"},
            {fk_marca: marcasPorDescricao["Jeep"], descricao: "RENEGADE"},
            {fk_marca: marcasPorDescricao["Jeep"], descricao: "WRANGLER"},
            {fk_marca: marcasPorDescricao["Jinbei"], descricao: "TOPIC"},
            {fk_marca: marcasPorDescricao["Jpx"], descricao: "MONTEZ"},
            {fk_marca: marcasPorDescricao["Kaiser"], descricao: "HENRY J"},
            {fk_marca: marcasPorDescricao["Kia"], descricao: "BESTA"},
            {fk_marca: marcasPorDescricao["Kia"], descricao: "BONGO"},
            {fk_marca: marcasPorDescricao["Kia"], descricao: "CADENZA"},
            {fk_marca: marcasPorDescricao["Kia"], descricao: "CARENS"},
            {fk_marca: marcasPorDescricao["Kia"], descricao: "CARNIVAL"},
            {fk_marca: marcasPorDescricao["Kia"], descricao: "CERATO"},
            {fk_marca: marcasPorDescricao["Kia"], descricao: "CLARUS"},
            {fk_marca: marcasPorDescricao["Kia"], descricao: "MAGENTIS"},
            {fk_marca: marcasPorDescricao["Kia"], descricao: "MOHAVE"},
            {fk_marca: marcasPorDescricao["Kia"], descricao: "OPIRUS"},
            {fk_marca: marcasPorDescricao["Kia"], descricao: "OPTIMA"},
            {fk_marca: marcasPorDescricao["Kia"], descricao: "PICANTO"},
            {fk_marca: marcasPorDescricao["Kia"], descricao: "QUORIS"},
            {fk_marca: marcasPorDescricao["Kia"], descricao: "RIO"},
            {fk_marca: marcasPorDescricao["Kia"], descricao: "SHUMA"},
            {fk_marca: marcasPorDescricao["Kia"], descricao: "SORENTO"},
            {fk_marca: marcasPorDescricao["Kia"], descricao: "SOUL"},
            {fk_marca: marcasPorDescricao["Kia"], descricao: "SPORTAGE"},
            {fk_marca: marcasPorDescricao["Lada"], descricao: "NIVA"},
            {fk_marca: marcasPorDescricao["Lamborghini"], descricao: "AVENTADOR"},
            {fk_marca: marcasPorDescricao["Lamborghini"], descricao: "GALLARDO"},
            {fk_marca: marcasPorDescricao["Lamborghini"], descricao: "HURACÁN"},
            {fk_marca: marcasPorDescricao["Land Rover"], descricao: "DEFENDER"},
            {fk_marca: marcasPorDescricao["Land Rover"], descricao: "DISCOVERY"},
            {fk_marca: marcasPorDescricao["Land Rover"], descricao: "DISCOVERY 2"},
            {fk_marca: marcasPorDescricao["Land Rover"], descricao: "DISCOVERY 3"},
            {fk_marca: marcasPorDescricao["Land Rover"], descricao: "DISCOVERY 4"},
            {fk_marca: marcasPorDescricao["Land Rover"], descricao: "DISCOVERY SPORT"},
            {fk_marca: marcasPorDescricao["Land Rover"], descricao: "FREELANDER"},
            {fk_marca: marcasPorDescricao["Land Rover"], descricao: "FREELANDER 2"},
            {fk_marca: marcasPorDescricao["Land Rover"], descricao: "RANGE ROVER"},
            {fk_marca: marcasPorDescricao["Land Rover"], descricao: "RANGE ROVER EVOQUE"},
            {fk_marca: marcasPorDescricao["Land Rover"], descricao: "RANGE ROVER SPORT"},
            {fk_marca: marcasPorDescricao["Land Rover"], descricao: "RANGE ROVER VOGUE"},
            {fk_marca: marcasPorDescricao["Land Rover"], descricao: "SÉRIE I"},
            {fk_marca: marcasPorDescricao["Landwind"], descricao: "X8"},
            {fk_marca: marcasPorDescricao["Lexus"], descricao: "CT200H"},
            {fk_marca: marcasPorDescricao["Lexus"], descricao: "ES"},
            {fk_marca: marcasPorDescricao["Lexus"], descricao: "ES 330"},
            {fk_marca: marcasPorDescricao["Lexus"], descricao: "ES 350"},
            {fk_marca: marcasPorDescricao["Lexus"], descricao: "GS"},
            {fk_marca: marcasPorDescricao["Lexus"], descricao: "GS 350"},
            {fk_marca: marcasPorDescricao["Lexus"], descricao: "IS 250"},
            {fk_marca: marcasPorDescricao["Lexus"], descricao: "IS250 F-SPORT"},
            {fk_marca: marcasPorDescricao["Lexus"], descricao: "IS300"},
            {fk_marca: marcasPorDescricao["Lexus"], descricao: "LS"},
            {fk_marca: marcasPorDescricao["Lexus"], descricao: "LS 460 L"},
            {fk_marca: marcasPorDescricao["Lexus"], descricao: "NX 200T"},
            {fk_marca: marcasPorDescricao["Lexus"], descricao: "RX 330"},
            {fk_marca: marcasPorDescricao["Lexus"], descricao: "RX 350"},
            {fk_marca: marcasPorDescricao["Lexus"], descricao: "RX350 F-SPORT"},
            {fk_marca: marcasPorDescricao["Lexus"], descricao: "SC 400"},
            {fk_marca: marcasPorDescricao["Lifan"], descricao: "320"},
            {fk_marca: marcasPorDescricao["Lifan"], descricao: "530"},
            {fk_marca: marcasPorDescricao["Lifan"], descricao: "620"},
            {fk_marca: marcasPorDescricao["Lifan"], descricao: "FOISON"},
            {fk_marca: marcasPorDescricao["Lifan"], descricao: "X60"},
            {fk_marca: marcasPorDescricao["Lincoln"], descricao: "CONTINENTAL"},
            {fk_marca: marcasPorDescricao["Lincoln"], descricao: "LS"},
            {fk_marca: marcasPorDescricao["Lincoln"], descricao: "MARK VIII"},
            {fk_marca: marcasPorDescricao["Lincoln"], descricao: "NAVIGATOR"},
            {fk_marca: marcasPorDescricao["Lincoln"], descricao: "TOWN CAR"},
            {fk_marca: marcasPorDescricao["Lobini"], descricao: "H1"},
            {fk_marca: marcasPorDescricao["Lotus"], descricao: "ELISE"},
            {fk_marca: marcasPorDescricao["Lotus"], descricao: "EXIGE"},
            {fk_marca: marcasPorDescricao["Mahindra"], descricao: "PICKUP"},
            {fk_marca: marcasPorDescricao["Mahindra"], descricao: "SCORPIO"},
            {fk_marca: marcasPorDescricao["Mahindra"], descricao: "SUV"},
            {fk_marca: marcasPorDescricao["Marcopolo"], descricao: "VOLARE"},
            {fk_marca: marcasPorDescricao["Maserati"], descricao: "3200"},
            {fk_marca: marcasPorDescricao["Maserati"], descricao: "COUPÉ"},
            {fk_marca: marcasPorDescricao["Maserati"], descricao: "GHIBLI"},
            {fk_marca: marcasPorDescricao["Maserati"], descricao: "GRAN TURISMO"},
            {fk_marca: marcasPorDescricao["Maserati"], descricao: "GRANCABRIO"},
            {fk_marca: marcasPorDescricao["Maserati"], descricao: "GRANSPORT"},
            {fk_marca: marcasPorDescricao["Maserati"], descricao: "QUATTROPORTE"},
            {fk_marca: marcasPorDescricao["Maserati"], descricao: "SPYDER"},
            {fk_marca: marcasPorDescricao["Matra"], descricao: "PICK-UP"},
            {fk_marca: marcasPorDescricao["Mazda"], descricao: "626"},
            {fk_marca: marcasPorDescricao["Mazda"], descricao: "MPV"},
            {fk_marca: marcasPorDescricao["Mazda"], descricao: "MX-3"},
            {fk_marca: marcasPorDescricao["Mazda"], descricao: "MX-5"},
            {fk_marca: marcasPorDescricao["Mclaren"], descricao: "MP4-12C"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "170 S"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "180 D"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "190 E"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "220"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "220 S"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "230 E"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "250"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "250 S"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "260 E"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "280 CE"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "280 E"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "280 S"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "280 SE"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "280 SL"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "300 CE"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "300 E"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "300 SD"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "300 SEL"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "300 SL"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "300 TD"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "300 TE"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "320 CE"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "320 E"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "320 SL"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "350 SL"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "450 SL"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "450 SLC"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "500 SE"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "500 SEL"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "500 SL"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "560 SEL"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "A 190"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "A 200"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "A 250"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "A 45 AMG"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "AMG GT"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "B 170"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "B 180"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "B 200"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "C 180"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "C 180 K"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "C 200"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "C 200 K"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "C 220"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "C 230"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "C 230 K"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "C 240"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "C 250"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "C 280"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "C 300"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "C 320"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "C 32K AMG"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "C 350"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "C 36 AMG"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "C 450"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "C 55 AMG"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "C 63 AMG"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "CL 500"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "CL 55 AMG"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "CL 600"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "CL 63 AMG"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "CL 65 AMG"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "CLA 200"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "CLA 250"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "CLA 45 AMG"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "CLASSE A"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "CLC 200"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "CLC 200 K"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "CLK 230"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "CLK 320"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "CLK 350"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "CLK 430"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "CLK 500"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "CLS 350"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "CLS 400"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "CLS 500"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "CLS 63 AMG"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "E 220"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "E 240"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "E 250"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "E 320"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "E 350"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "E 400"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "E 420"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "E 430"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "E 500"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "E 55 AMG"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "E 63 AMG"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "G 500"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "G 55 AMG"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "G 63 AMG"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "GL 350"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "GL 500"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "GL 63 AMG"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "GLA 200"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "GLA 250"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "GLA 45 AMG"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "GLK 220"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "GLK 280"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "GLK 300"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "MICROÔNIBUS"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "ML 320"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "ML 350"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "ML 430"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "ML 500"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "ML 63 AMG"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "R 500"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "S 320"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "S 350"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "S 400"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "S 500"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "S 500 L"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "S 600"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "S 63 AMG"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "S 65 AMG"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "SL 320"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "SL 350"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "SL 400"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "SL 500"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "SL 55 AMG"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "SL 600"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "SL 63 AMG"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "SL 65 AMG"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "SLK 200"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "SLK 230"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "SLK 250"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "SLK 300"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "SLK 320"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "SLK 350"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "SLK 55 AMG"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "SLS AMG"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "SPRINTER"},
            {fk_marca: marcasPorDescricao["Mercedes-benz"], descricao: "VITO"},
            {fk_marca: marcasPorDescricao["Mercury"], descricao: "COUGAR"},
            {fk_marca: marcasPorDescricao["Mercury"], descricao: "GRAND MARQUIS"},
            {fk_marca: marcasPorDescricao["Mercury"], descricao: "MONTEREY"},
            {fk_marca: marcasPorDescricao["Mg"], descricao: "MG 550"},
            {fk_marca: marcasPorDescricao["Mg"], descricao: "MG 6"},
            {fk_marca: marcasPorDescricao["Mg"], descricao: "MGB"},
            {fk_marca: marcasPorDescricao["Mg"], descricao: "MGF"},
            {fk_marca: marcasPorDescricao["Mg"], descricao: "TD"},
            {fk_marca: marcasPorDescricao["Mini"], descricao: "COOPER"},
            {fk_marca: marcasPorDescricao["Mini"], descricao: "COUNTRYMAN"},
            {fk_marca: marcasPorDescricao["Mini"], descricao: "JOHN COOPER WORKS"},
            {fk_marca: marcasPorDescricao["Mini"], descricao: "MORRIS"},
            {fk_marca: marcasPorDescricao["Mini"], descricao: "ONE"},
            {fk_marca: marcasPorDescricao["Mini"], descricao: "PACEMAN"},
            {fk_marca: marcasPorDescricao["Mini"], descricao: "ROADSTER"},
            {fk_marca: marcasPorDescricao["Mitsubishi"], descricao: "3000 GT"},
            {fk_marca: marcasPorDescricao["Mitsubishi"], descricao: "AIRTREK"},
            {fk_marca: marcasPorDescricao["Mitsubishi"], descricao: "ASX"},
            {fk_marca: marcasPorDescricao["Mitsubishi"], descricao: "COLT"},
            {fk_marca: marcasPorDescricao["Mitsubishi"], descricao: "ECLIPSE"},
            {fk_marca: marcasPorDescricao["Mitsubishi"], descricao: "GALANT"},
            {fk_marca: marcasPorDescricao["Mitsubishi"], descricao: "GRANDIS"},
            {fk_marca: marcasPorDescricao["Mitsubishi"], descricao: "L200"},
            {fk_marca: marcasPorDescricao["Mitsubishi"], descricao: "L200 OUTDOOR"},
            {fk_marca: marcasPorDescricao["Mitsubishi"], descricao: "L200 SAVANA"},
            {fk_marca: marcasPorDescricao["Mitsubishi"], descricao: "L200 TRITON"},
            {fk_marca: marcasPorDescricao["Mitsubishi"], descricao: "LANCER"},
            {fk_marca: marcasPorDescricao["Mitsubishi"], descricao: "OUTLANDER"},
            {fk_marca: marcasPorDescricao["Mitsubishi"], descricao: "PAJERO"},
            {fk_marca: marcasPorDescricao["Mitsubishi"], descricao: "PAJERO DAKAR"},
            {fk_marca: marcasPorDescricao["Mitsubishi"], descricao: "PAJERO FULL"},
            {fk_marca: marcasPorDescricao["Mitsubishi"], descricao: "PAJERO IO"},
            {fk_marca: marcasPorDescricao["Mitsubishi"], descricao: "PAJERO SPORT"},
            {fk_marca: marcasPorDescricao["Mitsubishi"], descricao: "PAJERO TR4"},
            {fk_marca: marcasPorDescricao["Mitsubishi"], descricao: "SPACE WAGON"},
            {fk_marca: marcasPorDescricao["Miura"], descricao: "BG"},
            {fk_marca: marcasPorDescricao["Morris"], descricao: "1300"},
            {fk_marca: marcasPorDescricao["Morris"], descricao: "MINI"},
            {fk_marca: marcasPorDescricao["Mp Lafer"], descricao: "CLASSICO"},
            {fk_marca: marcasPorDescricao["Nissan"], descricao: "350Z"},
            {fk_marca: marcasPorDescricao["Nissan"], descricao: "370Z"},
            {fk_marca: marcasPorDescricao["Nissan"], descricao: "ALTIMA"},
            {fk_marca: marcasPorDescricao["Nissan"], descricao: "ARMADA"},
            {fk_marca: marcasPorDescricao["Nissan"], descricao: "D 21"},
            {fk_marca: marcasPorDescricao["Nissan"], descricao: "FRONTIER"},
            {fk_marca: marcasPorDescricao["Nissan"], descricao: "GRAND LIVINA"},
            {fk_marca: marcasPorDescricao["Nissan"], descricao: "GT-R"},
            {fk_marca: marcasPorDescricao["Nissan"], descricao: "JUKE"},
            {fk_marca: marcasPorDescricao["Nissan"], descricao: "LIVINA"},
            {fk_marca: marcasPorDescricao["Nissan"], descricao: "MARCH"},
            {fk_marca: marcasPorDescricao["Nissan"], descricao: "MAXIMA"},
            {fk_marca: marcasPorDescricao["Nissan"], descricao: "MURANO"},
            {fk_marca: marcasPorDescricao["Nissan"], descricao: "PATHFINDER"},
            {fk_marca: marcasPorDescricao["Nissan"], descricao: "QUEST"},
            {fk_marca: marcasPorDescricao["Nissan"], descricao: "SENTRA"},
            {fk_marca: marcasPorDescricao["Nissan"], descricao: "TERRANO"},
            {fk_marca: marcasPorDescricao["Nissan"], descricao: "TIIDA"},
            {fk_marca: marcasPorDescricao["Nissan"], descricao: "VERSA"},
            {fk_marca: marcasPorDescricao["Nissan"], descricao: "XTERRA"},
            {fk_marca: marcasPorDescricao["Nissan"], descricao: "X-TRAIL"},
            {fk_marca: marcasPorDescricao["Oldsmobile"], descricao: "CUTLASS SUPREME"},
            {fk_marca: marcasPorDescricao["Oldsmobile"], descricao: "TORONADO"},
            {fk_marca: marcasPorDescricao["Opel"], descricao: "GT"},
            {fk_marca: marcasPorDescricao["Opel"], descricao: "KADETT"},
            {fk_marca: marcasPorDescricao["Packard"], descricao: "SIX"},
            {fk_marca: marcasPorDescricao["Pag"], descricao: "NICK"},
            {fk_marca: marcasPorDescricao["Peugeot"], descricao: "106"},
            {fk_marca: marcasPorDescricao["Peugeot"], descricao: "2008"},
            {fk_marca: marcasPorDescricao["Peugeot"], descricao: "206"},
            {fk_marca: marcasPorDescricao["Peugeot"], descricao: "207"},
            {fk_marca: marcasPorDescricao["Peugeot"], descricao: "208"},
            {fk_marca: marcasPorDescricao["Peugeot"], descricao: "3008"},
            {fk_marca: marcasPorDescricao["Peugeot"], descricao: "306"},
            {fk_marca: marcasPorDescricao["Peugeot"], descricao: "307"},
            {fk_marca: marcasPorDescricao["Peugeot"], descricao: "308"},
            {fk_marca: marcasPorDescricao["Peugeot"], descricao: "308cc"},
            {fk_marca: marcasPorDescricao["Peugeot"], descricao: "406"},
            {fk_marca: marcasPorDescricao["Peugeot"], descricao: "407"},
            {fk_marca: marcasPorDescricao["Peugeot"], descricao: "408"},
            {fk_marca: marcasPorDescricao["Peugeot"], descricao: "504"},
            {fk_marca: marcasPorDescricao["Peugeot"], descricao: "508"},
            {fk_marca: marcasPorDescricao["Peugeot"], descricao: "605"},
            {fk_marca: marcasPorDescricao["Peugeot"], descricao: "607"},
            {fk_marca: marcasPorDescricao["Peugeot"], descricao: "807"},
            {fk_marca: marcasPorDescricao["Peugeot"], descricao: "BOXER"},
            {fk_marca: marcasPorDescricao["Peugeot"], descricao: "HOGGAR"},
            {fk_marca: marcasPorDescricao["Peugeot"], descricao: "PARTNER"},
            {fk_marca: marcasPorDescricao["Peugeot"], descricao: "RCZ"},
            {fk_marca: marcasPorDescricao["Plymouth"], descricao: "ACCLAIM"},
            {fk_marca: marcasPorDescricao["Plymouth"], descricao: "BARRACUDA"},
            {fk_marca: marcasPorDescricao["Pontiac"], descricao: "FIREBIRD"},
            {fk_marca: marcasPorDescricao["Pontiac"], descricao: "FORMULA 400"},
            {fk_marca: marcasPorDescricao["Pontiac"], descricao: "SOLSTICE"},
            {fk_marca: marcasPorDescricao["Porsche"], descricao: "356"},
            {fk_marca: marcasPorDescricao["Porsche"], descricao: "911"},
            {fk_marca: marcasPorDescricao["Porsche"], descricao: "914"},
            {fk_marca: marcasPorDescricao["Porsche"], descricao: "928"},
            {fk_marca: marcasPorDescricao["Porsche"], descricao: "BOXSTER"},
            {fk_marca: marcasPorDescricao["Porsche"], descricao: "CAYENNE"},
            {fk_marca: marcasPorDescricao["Porsche"], descricao: "CAYMAN"},
            {fk_marca: marcasPorDescricao["Porsche"], descricao: "CAYMAN R"},
            {fk_marca: marcasPorDescricao["Porsche"], descricao: "CAYMAN S"},
            {fk_marca: marcasPorDescricao["Porsche"], descricao: "MACAN"},
            {fk_marca: marcasPorDescricao["Porsche"], descricao: "PANAMERA"},
            {fk_marca: marcasPorDescricao["Porsche"], descricao: "SPYDER 500"},
            {fk_marca: marcasPorDescricao["Porsche"], descricao: "SPYDER 550"},
            {fk_marca: marcasPorDescricao["Puma"], descricao: "AMV"},
            {fk_marca: marcasPorDescricao["Puma"], descricao: "GT"},
            {fk_marca: marcasPorDescricao["Puma"], descricao: "GTB/S2"},
            {fk_marca: marcasPorDescricao["Puma"], descricao: "GTC"},
            {fk_marca: marcasPorDescricao["Puma"], descricao: "GTE"},
            {fk_marca: marcasPorDescricao["Puma"], descricao: "GTS"},
            {fk_marca: marcasPorDescricao["Rely"], descricao: "LINK"},
            {fk_marca: marcasPorDescricao["Rely"], descricao: "PICK-UP"},
            {fk_marca: marcasPorDescricao["Rely"], descricao: "VAN"},
            {fk_marca: marcasPorDescricao["Renault"], descricao: "19"},
            {fk_marca: marcasPorDescricao["Renault"], descricao: "CLIO"},
            {fk_marca: marcasPorDescricao["Renault"], descricao: "DAUPHINE"},
            {fk_marca: marcasPorDescricao["Renault"], descricao: "DUSTER"},
            {fk_marca: marcasPorDescricao["Renault"], descricao: "DUSTER OROCH"},
            {fk_marca: marcasPorDescricao["Renault"], descricao: "EXPRESS"},
            {fk_marca: marcasPorDescricao["Renault"], descricao: "FLUENCE"},
            {fk_marca: marcasPorDescricao["Renault"], descricao: "GORDINI"},
            {fk_marca: marcasPorDescricao["Renault"], descricao: "GRAND SCÉNIC"},
            {fk_marca: marcasPorDescricao["Renault"], descricao: "KANGOO"},
            {fk_marca: marcasPorDescricao["Renault"], descricao: "LAGUNA"},
            {fk_marca: marcasPorDescricao["Renault"], descricao: "LOGAN"},
            {fk_marca: marcasPorDescricao["Renault"], descricao: "MASTER"},
            {fk_marca: marcasPorDescricao["Renault"], descricao: "MÉGANE"},
            {fk_marca: marcasPorDescricao["Renault"], descricao: "SANDERO"},
            {fk_marca: marcasPorDescricao["Renault"], descricao: "SCÉNIC"},
            {fk_marca: marcasPorDescricao["Renault"], descricao: "SYMBOL"},
            {fk_marca: marcasPorDescricao["Renault"], descricao: "TRAFIC"},
            {fk_marca: marcasPorDescricao["Renault"], descricao: "TWINGO"},
            {fk_marca: marcasPorDescricao["Reva-i"], descricao: "STANDARD"},
            {fk_marca: marcasPorDescricao["Rolls-royce"], descricao: "CORNICHE"},
            {fk_marca: marcasPorDescricao["Rolls-royce"], descricao: "GHOST"},
            {fk_marca: marcasPorDescricao["Rolls-royce"], descricao: "PHANTOM"},
            {fk_marca: marcasPorDescricao["Rolls-royce"], descricao: "SILVER SHADOW"},
            {fk_marca: marcasPorDescricao["Rolls-royce"], descricao: "SILVER SHADOW II"},
            {fk_marca: marcasPorDescricao["Rolls-royce"], descricao: "SILVER SPUR"},
            {fk_marca: marcasPorDescricao["Rolls-royce"], descricao: "SILVER WRAITH II"},
            {fk_marca: marcasPorDescricao["Rolls-royce"], descricao: "WRAITH"},
            {fk_marca: marcasPorDescricao["Romi"], descricao: "ROMI-ISETTA"},
            {fk_marca: marcasPorDescricao["Saab"], descricao: "9000"},
            {fk_marca: marcasPorDescricao["Santa Matilde"], descricao: "SM 4.1"},
            {fk_marca: marcasPorDescricao["Saturn"], descricao: "SL-2"},
            {fk_marca: marcasPorDescricao["Seat"], descricao: "CORDOBA"},
            {fk_marca: marcasPorDescricao["Seat"], descricao: "IBIZA"},
            {fk_marca: marcasPorDescricao["Seat"], descricao: "INCA"},
            {fk_marca: marcasPorDescricao["Selvagem"], descricao: "S"},
            {fk_marca: marcasPorDescricao["Shelby"], descricao: "COBRA"},
            {fk_marca: marcasPorDescricao["Shelby"], descricao: "GT 500"},
            {fk_marca: marcasPorDescricao["Shineray"], descricao: "A7"},
            {fk_marca: marcasPorDescricao["Shineray"], descricao: "A9"},
            {fk_marca: marcasPorDescricao["Shineray"], descricao: "A9 CARGO"},
            {fk_marca: marcasPorDescricao["Shineray"], descricao: "SY1020"},
            {fk_marca: marcasPorDescricao["Shineray"], descricao: "T20"},
            {fk_marca: marcasPorDescricao["Shineray"], descricao: "T20 BAÚ"},
            {fk_marca: marcasPorDescricao["Shineray"], descricao: "T22"},
            {fk_marca: marcasPorDescricao["Shineray"], descricao: "X30"},
            {fk_marca: marcasPorDescricao["Smart"], descricao: "FORTWO"},
            {fk_marca: marcasPorDescricao["Ssangyong"], descricao: "ACTYON"},
            {fk_marca: marcasPorDescricao["Ssangyong"], descricao: "ACTYON SPORTS"},
            {fk_marca: marcasPorDescricao["Ssangyong"], descricao: "KORANDO"},
            {fk_marca: marcasPorDescricao["Ssangyong"], descricao: "KYRON"},
            {fk_marca: marcasPorDescricao["Ssangyong"], descricao: "REXTON"},
            {fk_marca: marcasPorDescricao["Ssangyong"], descricao: "REXTON II"},
            {fk_marca: marcasPorDescricao["Standard"], descricao: "VANGUARD"},
            {fk_marca: marcasPorDescricao["Studebaker"], descricao: "STUDEBAKER"},
            {fk_marca: marcasPorDescricao["Subaru"], descricao: "FORESTER"},
            {fk_marca: marcasPorDescricao["Subaru"], descricao: "IMPREZA"},
            {fk_marca: marcasPorDescricao["Subaru"], descricao: "LEGACY"},
            {fk_marca: marcasPorDescricao["Subaru"], descricao: "OUTBACK"},
            {fk_marca: marcasPorDescricao["Subaru"], descricao: "SVX"},
            {fk_marca: marcasPorDescricao["Subaru"], descricao: "TRIBECA"},
            {fk_marca: marcasPorDescricao["Subaru"], descricao: "VIVIO"},
            {fk_marca: marcasPorDescricao["Subaru"], descricao: "XV"},
            {fk_marca: marcasPorDescricao["Suzuki"], descricao: "GRAND VITARA"},
            {fk_marca: marcasPorDescricao["Suzuki"], descricao: "IGNIS"},
            {fk_marca: marcasPorDescricao["Suzuki"], descricao: "JIMNY"},
            {fk_marca: marcasPorDescricao["Suzuki"], descricao: "SAMURAI"},
            {fk_marca: marcasPorDescricao["Suzuki"], descricao: "S-CROSS"},
            {fk_marca: marcasPorDescricao["Suzuki"], descricao: "SIDEKICK"},
            {fk_marca: marcasPorDescricao["Suzuki"], descricao: "SWIFT"},
            {fk_marca: marcasPorDescricao["Suzuki"], descricao: "SX4"},
            {fk_marca: marcasPorDescricao["Suzuki"], descricao: "VITARA"},
            {fk_marca: marcasPorDescricao["Tac"], descricao: "STARK"},
            {fk_marca: marcasPorDescricao["Tesla"], descricao: "MODEL S"},
            {fk_marca: marcasPorDescricao["Toyota"], descricao: "AVALON"},
            {fk_marca: marcasPorDescricao["Toyota"], descricao: "BANDEIRANTE"},
            {fk_marca: marcasPorDescricao["Toyota"], descricao: "CAMRY"},
            {fk_marca: marcasPorDescricao["Toyota"], descricao: "COROLLA"},
            {fk_marca: marcasPorDescricao["Toyota"], descricao: "CORONA"},
            {fk_marca: marcasPorDescricao["Toyota"], descricao: "ETIOS"},
            {fk_marca: marcasPorDescricao["Toyota"], descricao: "ETIOS CROSS"},
            {fk_marca: marcasPorDescricao["Toyota"], descricao: "FIELDER"},
            {fk_marca: marcasPorDescricao["Toyota"], descricao: "FJ CRUISER"},
            {fk_marca: marcasPorDescricao["Toyota"], descricao: "HILUX"},
            {fk_marca: marcasPorDescricao["Toyota"], descricao: "HILUX SW4"},
            {fk_marca: marcasPorDescricao["Toyota"], descricao: "LAND CRUISER PRADO"},
            {fk_marca: marcasPorDescricao["Toyota"], descricao: "MR-2"},
            {fk_marca: marcasPorDescricao["Toyota"], descricao: "PASEO"},
            {fk_marca: marcasPorDescricao["Toyota"], descricao: "PREVIA"},
            {fk_marca: marcasPorDescricao["Toyota"], descricao: "PRIUS"},
            {fk_marca: marcasPorDescricao["Toyota"], descricao: "RAV4"},
            {fk_marca: marcasPorDescricao["Toyota"], descricao: "SIENNA"},
            {fk_marca: marcasPorDescricao["Toyota"], descricao: "TUNDRA"},
            {fk_marca: marcasPorDescricao["Toyota"], descricao: "VENZA"},
            {fk_marca: marcasPorDescricao["Triumph"], descricao: "SPITFIRE"},
            {fk_marca: marcasPorDescricao["Troller"], descricao: "RF"},
            {fk_marca: marcasPorDescricao["Troller"], descricao: "T4"},
            {fk_marca: marcasPorDescricao["Troller"], descricao: "T5"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "1300"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "1500"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "1600"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "AMAROK"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "APOLLO"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "BORA"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "BRASILIA"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "BUGGY"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "CROSS UP"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "CROSSFOX"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "EOS"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "EUROVAN"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "FOX"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "FUSCA"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "GOL"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "GOLF"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "JETTA"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "KARMANN-GHIA"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "KOMBI"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "LOGUS"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "NEW BEETLE"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "PARATI"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "PASSAT"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "PASSAT VARIANT"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "POINTER"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "POLO"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "POLO SEDAN"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "QUANTUM"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "SANTANA"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "SAVEIRO"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "SCIROCCO"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "SP2"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "SPACE CROSS"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "SPACEFOX"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "TIGUAN"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "TL"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "TOUAREG"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "UP"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "VAN"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "VARIANT"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "VARIANT II"},
            {fk_marca: marcasPorDescricao["Volkswagen"], descricao: "VOYAGE"},
            {fk_marca: marcasPorDescricao["Volvo"], descricao: "460"},
            {fk_marca: marcasPorDescricao["Volvo"], descricao: "850"},
            {fk_marca: marcasPorDescricao["Volvo"], descricao: "960"},
            {fk_marca: marcasPorDescricao["Volvo"], descricao: "C30"},
            {fk_marca: marcasPorDescricao["Volvo"], descricao: "S40"},
            {fk_marca: marcasPorDescricao["Volvo"], descricao: "S60"},
            {fk_marca: marcasPorDescricao["Volvo"], descricao: "S80"},
            {fk_marca: marcasPorDescricao["Volvo"], descricao: "V40"},
            {fk_marca: marcasPorDescricao["Volvo"], descricao: "V50"},
            {fk_marca: marcasPorDescricao["Volvo"], descricao: "V60"},
            {fk_marca: marcasPorDescricao["Volvo"], descricao: "V70"},
            {fk_marca: marcasPorDescricao["Volvo"], descricao: "XC60"},
            {fk_marca: marcasPorDescricao["Volvo"], descricao: "XC70"},
            {fk_marca: marcasPorDescricao["Volvo"], descricao: "XC90"},
            {fk_marca: marcasPorDescricao["Way Brasil"], descricao: "BUGGY"},
            {fk_marca: marcasPorDescricao["Whippet"], descricao: "96A"},
            {fk_marca: marcasPorDescricao["Willys"], descricao: "AERO-WILLYS"},
            {fk_marca: marcasPorDescricao["Willys"], descricao: "INTERLAGOS"},
            {fk_marca: marcasPorDescricao["Willys"], descricao: "JEEP"},
            {fk_marca: marcasPorDescricao["Willys"], descricao: "RURAL"},
            {fk_marca: marcasPorDescricao["Willys Overland"], descricao: "CJ2A"},
            {fk_marca: marcasPorDescricao["Willys Overland"], descricao: "JEEP"}
        ],
        function(err) {
            if (err) throw err;
            next();
        });

    });
  
};

exports.down = function(next) {
      db.modelo.find().remove(function(err) {
            if (err) throw err;
            next();
      })
};
